<?php

namespace Paypal\Api;

class IncentiveSiteAppliedOnType
{
    const __default = 'INCENTIVESITEAPPLIEDONUNKNOWN';
    const INCENTIVESITEAPPLIEDONUNKNOWN = 'INCENTIVE-SITE-APPLIED-ON-UNKNOWN';
    const INCENTIVESITEAPPLIEDONMERCHANT = 'INCENTIVE-SITE-APPLIED-ON-MERCHANT';
    const INCENTIVESITEAPPLIEDONPAYPAL = 'INCENTIVE-SITE-APPLIED-ON-PAYPAL';


}
